appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: ppJhDb2uZGGVaiBReT0cOtKx5eEyTe+Cqujuqs6SDzkT3ul60O8xXeb4RNOvAyJ817roJrhK15ZN3WyB4r27gM9fzW8nHu5mnBIv3NyWhfrYlm7PXjEueMDSLmF2xtLOIDWxai+QmofPdew2vwvOavc6vGdkfVw7R6ax8aGgnrW8hpH8X8G5E10aotIb1kSsK2Qn9rGCMS4ITanezV5SidvcD6jw9Q/DqdhR5ad+ozXBDeduVGxr7FKsH2M07uXQNNlM6NyGbYMDdlOmj9Dy7addg3i5Ii49LZDSPDCQsfNJW9bQbpCUyDuZX2a1llHcPwqXev2Kw+T0U0gKZTTTDSM9Tz8stCnkwoWClu74uCy6pMAR9DzVP2ZOAPkCLmGNkDmW19LKv+Hz0UC7H9ExH94rptwoKZ+S5yHUuH1mqVt2gwm8cWjBS2Zksh14DLWnPf4RtPpQaA5sfcqsJHBEPwqgmEjJEtA98g8nnUJwSr5DV/5XhqJ4/0U70W502URawbjNydDSFL+PegDqD0xAZ4LmWKEGAMOpqbbIumAqw+3LcIKogm6ar0Tsf27vKRi3vTNd3HSbuZ4iZyiDK/vZQvOhaoUxANgVCfZ8GAkeMjhiLeKaaQIByTCdxChWNlfueX8oSwnpmuDgXwKClL9JQnvhpkQDgJGlyKUYsk0gap0=
conda_forge_output_validation: true
